version: '3'
services:
  cloudflare-dns-server:
    build: .
    image: haocen/cloudflare-dns-server
    container_name: cloudflare-dns-server
    environment:
      - VERBOSITY=1
      - VERBOSITY_DETAILS=0
      - BLOCK_MALICIOUS=on
      - BLOCK_NSA=off
      - UNBLOCK=
      - LISTENINGPORT=53
      - PROVIDER=cloudflare
    ports:
      - 53:53/udp
    network_mode: bridge
